version: '3.7'

services:
  node:
    image: ai-node
    container_name: IAServe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./node:/node
    working_dir: /node
    restart: unless-stopped